Hometask 1
lwtztea/smart-home-2020 pull request #1
Opened 2020-03-13 15:12 UTC by lwtztea

2020-03-13 15:34 UTC, a-ivanov requested changes

2020-03-13 15:34 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
>          while (event != null) {
Нарушение SRP http://bit.ly/3aD3KAp

2020-03-13 15:34 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHomeStateReader.java
> +    public static SmartHome readJson(String path) throws IOException {
http://bit.ly/2v2kMZw leaky abstraction, исправьте

2020-03-13 15:34 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +            event = new SensorEventGenerator().getRandomSensorEvent();
На надо создавать лишние копии объектов http://bit.ly/2TBH1Pg просто вынесите эту логику в отдельный класс и передайте ему снаружи SensorEventGenerator как зависимость. Генератор можно сделать интерфейсом, например здесь у нас сначала будет RandomEventsGenerator, который мы используем для симуляции новых событий, в будущем можно добавить новую имплементацию, которая будет генерировать настоящие события из датчика.

2020-03-13 15:34 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/DoorEventHandler.java
> +        assert changedDoor != null;
Не используйте assert в бизнес логике. Он работает только при включённом флаге в JVM,те без него не будет работать и у вас тут появится NPE. assert можно использовать в местах, код которых точно не должен выполняться. Срабатывание assert может означать, что что-то совсем пошло не так.

2020-03-13 15:34 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/LightEventHandler.java
> +    private static void changeLightState(SensorEvent event, Room room, Light light) {
Этот метод кем-то используется?

2020-03-13 15:34 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/DoorEventHandler.java
> +        if (changedRoom.getName().equals("hall") && event.getType() == DOOR_CLOSED) {
Нарушение SRP http://bit.ly/2VO81g0

2020-03-21 12:45 UTC, lwtztea commented on src/main/java/ru/sbt/mipt/oop/LightEventHandler.java
> +    private static void changeLightState(SensorEvent event, Room room, Light light) {
Да, в методе handleSmartHomeEvent(), там в конце как раз меняется состояние света через этот метод

2020-03-21 12:47 UTC, merged