Hometask 4
lwtztea/smart-home-2020 pull request #5
Opened 2020-03-25 20:33 UTC by lwtztea

2020-03-30 15:03 UTC, a-ivanov requested changes

2020-03-30 15:03 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SpringConfiguration.java
> +public class SpringConfiguration {
Добавьте аннотацию `@Configuration` https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/annotation/Configuration.html

2020-03-30 15:03 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SensorEventAdapter.java
> +    private static final Map<String, SensorEventType> adaptedEventType = new HashMap<String, SensorEventType>() {
Передавайте эту мапу через аргумент в конструкторе. Саму мапу можно сконфигурировать бином в спринге.

2020-03-30 15:03 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        AbstractApplicationContext context = new AnnotationConfigApplicationContext(SpringConfiguration.class);
А где конфигурация с бинами ваших обработчиков из предыдущих заданий? https://bit.ly/2UrPgOg

2020-04-01 13:43 UTC, lwtztea commented on src/main/java/ru/sbt/mipt/oop/SpringConfiguration.java
> +public class SpringConfiguration {
исправила

2020-04-01 13:43 UTC, lwtztea commented on src/main/java/ru/sbt/mipt/oop/SensorEventAdapter.java
> +    private static final Map<String, SensorEventType> adaptedEventType = new HashMap<String, SensorEventType>() {
исправила

2020-04-01 13:43 UTC, lwtztea commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        AbstractApplicationContext context = new AnnotationConfigApplicationContext(SpringConfiguration.class);
исправила

2020-04-03 13:16 UTC, a-ivanov approved these changes

2020-04-03 13:16 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventHandlerAdapter.java
> +            handler.handleEvent(new SensorEvent(adaptedEventType.get(event.getEventType()), event.getObjectId()));
Надо проверять наличие ключа, иначе NPE.

2020-04-03 16:54 UTC, closed without merging

2020-04-06 14:15 UTC, a-ivanov commented
Замерджите коммиты из этого реквеста в master.